### ISSUE TITLE
websockets problem

### ISSUE THREAD

**Issue by claudesimo1990** [francislavoie/laravel-websockets-example#1]
Hi, i cannot connect to websockets server. Dashbord (http://localhost/laravel-websockets) dont work.
please help me.

<img width="1440" alt="Capture d’écran 2021-11-14 à 18 53 56" src="https://user-images.githubusercontent.com/45970298/141692561-ae3edb58-7b76-423f-8a0c-96d1daffc7bc.png">

**Comment by francislavoie** [comment]
You'll need to change the port by setting the env var mentioned here in your `.env` in the other root. https://github.com/francislavoie/laravel-websockets-example/blob/4aa8d64cf030289055d7b50e2856f90e05bd9a44/config/websockets.php#L16

I didn't use the dashboard when I wrote this example repo.

All the libs/containers in this are probably outdated at this point. Make sure to upgrade to the latest versions (including Caddy).

**Comment by claudesimo1990** [comment]
sorry which port should I use for this to work?

I wrote the port exposed by the container (6001)

**Comment by francislavoie** [comment]
The point of this setup is that Caddy proxies websocket requests on the same port as HTTP. So if developing locally, port 80. For in production with HTTPS, port 443.

**Comment by claudesimo1990** [comment]
<img width="1440" alt="Capture d’écran 2021-11-14 à 19 51 26" src="https://user-images.githubusercontent.com/45970298/141694429-9d22e717-0d22-44a1-ab52-e68ddd704f15.png">

**Comment by claudesimo1990** [comment]
thank you i'm already receiving something new
